// Generated by CoffeeScript 1.8.0
(function() {
  this.SpideyAnimation = (function() {
    function SpideyAnimation() {}

    SpideyAnimation.prototype.xCentre = 250;

    SpideyAnimation.prototype.yCentre = 375;

    SpideyAnimation.prototype.getColour = function(x, y, padNum, padLedIdx, genIdx) {
      var colAr, colorIdx, colr, distFromCentre, i, _i;
      distFromCentre = Math.sqrt((x - this.xCentre) * (x - this.xCentre) + (y - this.yCentre) * (y - this.yCentre));
      colorIdx = distFromCentre + (100000 - genIdx) * 15;
      colr = "#";
      colAr = [];
      for (i = _i = 0; _i <= 2; i = ++_i) {
        colAr.push(Math.abs((Math.floor(colorIdx) + (i * 152)) % 256 - 128) + 30);
        colr += ("00" + colAr[i].toString(16)).substr(-2);
      }
      colr = "rgba(" + colAr[0].toString() + "," + colAr[1].toString() + "," + colAr[2].toString() + ",1.0)";
      return colr;
    };

    return SpideyAnimation;

  })();

}).call(this);
